name: Flask CI/CD Pipeline

# Trigger on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          uv pip install pytest
          uv sync

      # Step 4: Run tests
      #- name: Run tests
       # run:  uv run pytest

      # Step 5: Deploy to server via SSH
      - name: Deploy to server
        if: success() # Only deploy if tests pass
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key_path: /tmp/deploy_key
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/Stumartcot-Construction
            git pull 
            #pip install -r requirements.txt
            sudo systemctl restart stumarcot